import {
  DO_COMPLIANCE_CHECK_TOOL_CONFIG,
  PDF_GENERATION_TOOLS_CONFIG,
  STORE_ACCEPTANCE_CRITERIA_SECONDARY_TOOL_CONFIG,
  STORE_ACCEPTANCE_CRITERIA_TOOL_CONFIG,
  STORE_GO_LIVE_TOOL_CONFIG,
  STORE_INITIAL_SETUP_TOOL_CONFIG,
  STORE_IS_REGULATORY_CHECK_AT_EVERY_STEP_TOOL_CONFIG,
  STORE_LOAN_PARAMETERS_SECONDARY_TOOL_CONFIG,
  STORE_LOAN_PARAMETERS_TOOL_CONFIG,
  STORE_PRICING_SECONDARY_TOOL_CONFIG,
  STORE_PRICING_TOOL_CONFIG,
  STORE_REGULATORY_CHECK_SECONDARY_TOOL_CONFIG,
} from "./tools/tools-schemas";

export const toolsList = [
  STORE_INITIAL_SETUP_TOOL_CONFIG,
  STORE_IS_REGULATORY_CHECK_AT_EVERY_STEP_TOOL_CONFIG,
  STORE_LOAN_PARAMETERS_TOOL_CONFIG,
  STORE_ACCEPTANCE_CRITERIA_TOOL_CONFIG,
  STORE_PRICING_TOOL_CONFIG,
  STORE_REGULATORY_CHECK_SECONDARY_TOOL_CONFIG,
  STORE_GO_LIVE_TOOL_CONFIG,
  ...PDF_GENERATION_TOOLS_CONFIG,
];

export const toolsListCompatableCheck = [
  STORE_INITIAL_SETUP_TOOL_CONFIG,
  STORE_IS_REGULATORY_CHECK_AT_EVERY_STEP_TOOL_CONFIG,
  STORE_LOAN_PARAMETERS_SECONDARY_TOOL_CONFIG,
  STORE_ACCEPTANCE_CRITERIA_SECONDARY_TOOL_CONFIG,
  STORE_PRICING_SECONDARY_TOOL_CONFIG,
  STORE_GO_LIVE_TOOL_CONFIG,
  DO_COMPLIANCE_CHECK_TOOL_CONFIG,
  ...PDF_GENERATION_TOOLS_CONFIG,
];
